name: CI for React App with Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Generate documentation
      - name: Generate documentation
        run: npm run generate-docs

      # Zip both the code and the documentation
      - name: Zip code and documentation
        run: |
          zip -r code-and-docs.zip .  # Zip all files in the repo
          zip -r code-and-docs.zip ./docs  # Ensure docs are included

      # Upload code and documentation as an artifact
      - name: Upload code and documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-and-docs
          path: ./code-and-docs.zip

      # Determine the version (tag) for the release
      - name: Determine version
        id: determine_version
        run: |
          VERSION="v$(date +'%Y%m%d%H%M%S')"  # Generate a version based on timestamp (e.g., v20250113123045)
          echo "version=$VERSION" >> $GITHUB_ENV

      # Create a release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
          draft: false
          prerelease: false

      # Upload the code-and-docs.zip file to the release
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./code-and-docs.zip
          asset_name: code-and-docs.zip
          asset_content_type: application/zip
